# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zach Bethune - Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Zach Bethune - Associate Professor of Economics - Rice University
domain: zbethune.github.io
baseurl: "/" # the subpath of the site
# url: "https://zbethune.github.io" # the base hostname & protocol for the site
url: "https://www.zachbethune.com" # the base hostname & protocol for the site
og_image: /assets/img/zach_bethune.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching
    - name: Other
    - name: RISE Inflation Conference
      slug: /RISEconference


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: bethune@rice.edu
      link: mailto:bethune@rice.edu
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    - name: Twitter
      link: https://twitter.com/ZBethune
      username: "@ZBethune"
    # - name: Facebook
    #   link: https://facebook.com/YourFacebookUsername
    # - name: LinkedIn
    #   link: https://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: https://github.com/zbethune
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml
    - name: Scholar
      link: https://scholar.google.com/citations?user=-Y1OcgEAAAAJ
    - name: RePEc
      link: https://ideas.repec.org/f/pbe832.html

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
